[package]
name = "wall"
version = "0.0.1"
authors = ["Kristofer Lund <kristofer@fmckl.se>"]
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.2.4"
ic-cdk-macros = "0.2.4"
serde = "1.0.111"
sha2 = "0.9.5"
base64 = "0.9.3"
